server:  # Server settings.
  # Address to listen on.
  addr: ":5001"
  # TLS certificate and key.
  certificate: "/ssl/qy-auth-server.crt"
  key: "/ssl/qy.key"

token:  # Settings for the tokens.
  issuer: "AuthService"  # Must match issuer in the Registry config.
  expiration: 900

ldap_auth:
  addr: 172.28.90.32:10389
  # Setup tls connection method to be
  # "" or "none": the communication won't be encrypted
  # "always": setup LDAP over SSL/TLS
  # "starttls": sets StartTLS as the encryption method
  tls: none
  bind_dn: "uid=admin,ou=system"
  bind_password_file: "/ssl/pass.txt"
  base: "ou=Users,dc=WSO2,dc=ORG"
  filter: (&(uid=${account})(objectClass=person))
acl:
  - match: {account: "admin"}
    actions: ["*"]
    comment: "Admin has full access to everything."
  - match: {account: "/.+/", name: "${account}/*"}
    actions: ["*"]
    comment: "Logged in users have full access to images that are in their 'namespace'"
  - match: {account: "/.+/"}
    actions: ["pull"]
    comment: "Logged in users can pull all images."
  - match: {account: "", name: "hello-world"}
    actions: ["pull"]
    comment: "Anonymous users can pull \"hello-world\"."
