server:  # Server settings.
  # Address to listen on.
  addr: ":5001"
  # TLS certificate and key.
  certificate: "/ssl/qy-bundle.crt"
  key: "/ssl/qy.key"

token:  # Settings for the tokens.
  issuer: "AuthService"  # Must match issuer in the Registry config.
  expiration: 900
users:
  "admin":
    password: "$2y$05$B.x046DV3bvuwFgn0I42F.W/SbRU5fUoCbCGtjFl7S33aCUHNBxbq"
  "chyshao":
    password: "$2a$10$unZgGf5r8TWb16Auc48TzuVn1EyUVQqxw.kWioGInL3zW.bA0NlZu"
  "fxtang":
    password: "$2a$10$unZgGf5r8TWb16Auc48TzuVn1EyUVQqxw.kWioGInL3zW.bA0NlZu"  
  "ftwang":
    password: "$2a$10$unZgGf5r8TWb16Auc48TzuVn1EyUVQqxw.kWioGInL3zW.bA0NlZu"
  "junren":
    password: "$2a$10$unZgGf5r8TWb16Auc48TzuVn1EyUVQqxw.kWioGInL3zW.bA0NlZu"
  "hlyue":
    password: "$2a$10$unZgGf5r8TWb16Auc48TzuVn1EyUVQqxw.kWioGInL3zW.bA0NlZu"
  "hussein":
    password: "$2y$05$xN3hNmNlBIYpST7UzqwK/O5T1/JyXDGuJgKJzf4XuILmvX7L5ensa"
  "jwyu":
    password: "$2a$10$unZgGf5r8TWb16Auc48TzuVn1EyUVQqxw.kWioGInL3zW.bA0NlZu"
  "": {}  # Allow anonymous (no "docker login") access.

acl:
  # This will allow authenticated users to pull/push
  - match:
      account: /.+/
    actions: ['*']
